

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: ${CONFIG_URL}
      username: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
      fail-fast: false
  config:
    import: "optional:configserver:"

  datasource:
    url: "jdbc:postgresql://${USER_DATABASE_URL}/user_service"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      naming:
        physical-strategy: org.solowev.taskmanager.auth.utils.CustomNamingStrategy
      ddl-auto: none
    database: postgresql
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: tmp
            client-secret: riRQe1jNiCSkT1uUrI2yesqQLinhxcJl
            authorization-grant-type: authorization_code
            scope: openid, profile, tmp
            redirect-uri: http://${ACCOUNT_SERVICE_URL}/login/oauth2/code/keycloak
        provider:
          keycloak:
            authorization-uri: ${app.keycloak.realm.uri}/protocol/openid-connect/auth
            token-uri: ${app.keycloak.realm.uri}/protocol/openid-connect/token
            user-info-uri: ${app.keycloak.realm.uri}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.keycloak.realm.uri}/protocol/openid-connect/certs
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${app.keycloak.realm.uri}/protocol/openid-connect/certs

app:
  keycloak:
    realm:
      uri: http://${KEYCLOAK_URL}/auth/realms/taskmanagement-realm
  signing:
    key: ljH9ISvhCFjHdcxS2k8amKpXNNrKzpycX2g24G3jzp9ZTCsSB+kfo0QZKR8/sEZvVGObR342liSAvDU4P4Y/OA==
