spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://localhost:8090
      username: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
      fail-fast: true
  config:
    import: "optional:configserver:"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false