spring:
  application:
    name: discovery
  cloud:
    config:
      uri: ${CONFIG_URL}
      username: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
      fail-fast: true
  config:
    import: "optional:configserver:"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false