spring:
  application:
    name: gateway
  cloud:
    config:
      uri: ${CONFIG_URL}
      username: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
      fail-fast: true
  config:
    import: "optional:configserver:"