server:
  port: 8094
spring:
  application:
    name: user-service
  cloud:
    config:
      uri: ${CONFIG_URL}
      username: ${ADMIN_USER}
      password: ${ADMIN_PASSWORD}
      fail-fast: false
      allow-override: false
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_SERVICE_URL}/token/jwk/keys
  datasource:
    url: "jdbc:postgresql://${USER_DATABASE_URL}/user_service"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.solowev.taskmanager.base.CustomNamingStrategy
    database: postgresql
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create_user.sql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: true
  jackson:
    time-zone: Europe/Moscow