eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org.spring.framework: error
    org.hibernate: warn