server:
  port: 8093

spring:
  datasource:
    url: "jdbc:postgresql://${USER_DATABASE_URL}/auth"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      naming:
        physical-strategy: org.solowev.taskmanager.auth.utils.CustomNamingStrategy
      ddl-auto: none
    database: postgresql
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: true
  jackson:
    time-zone: Europe/Moscow

app:
  baseUrl: http://${AUTH_SERVICE_URL}
  keystore:
    file: keystore.p12
    alias: keystore
    pass: ${KEYSTORE_PASSWORD}
  jwt:
    refreshExpirationTime: 100000000
    expirationTime: 3600000