server:
  port: 8093

spring:
  datasource:
    url: "jdbc:postgresql://${USER_DATABASE_URL}/user_database"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      default_schema: tpm_user_service
      physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: postgresql